name: CI

on:
  - push
  - pull_request
  - workflow_dispatch

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: '-C debuginfo=0'

jobs:
  Check:
    runs-on: self-hosted

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Check formatting
        run: cargo fmt --all --check
      - name: Run Clippy
        run: cargo clippy --all -- -D warnings