name: release-please

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Publish:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y dh-make

      - name: Install cargo-deb
        run: cargo install cargo-deb

      - name: Build project
        run: |
          cargo deb -v
          mv target/release/oze-canopen-viewer-x64-ubuntu-24-04 ./
          mv target/debian/oze-canopen-viewer*.deb ./oze-canopen-viewer-x64-ubuntu-24-04.deb

      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload --clobber ${{ needs.release_please.outputs.tag_name }} oze-canopen-viewer*